OPENQASM 2.0;
include "qelib1.inc";
creg c[4];
qreg qregless[4];
reset qregless[0];
barrier qregless[0];
barrier qregless[0];
rz(pi/2) qregless[0];
sx qregless[0];
rz(pi/2) qregless[0];
barrier qregless[0];
rz(pi/2) qregless[0];
sx qregless[0];
rz(pi/2) qregless[0];
reset qregless[1];
barrier qregless[1];
barrier qregless[1];
rz(pi/2) qregless[1];
sx qregless[1];
rz(pi/2) qregless[1];
barrier qregless[1];
rz(pi/2) qregless[1];
sx qregless[1];
rz(pi/2) qregless[1];
reset qregless[2];
barrier qregless[2];
barrier qregless[2];
rz(pi/2) qregless[2];
sx qregless[2];
rz(pi/2) qregless[2];
barrier qregless[2];
rz(pi/2) qregless[2];
sx qregless[2];
rz(pi/2) qregless[2];
reset qregless[3];
barrier qregless[3];
rz(pi/2) qregless[3];
sx qregless[3];
rz(pi/2) qregless[3];
barrier qregless[3];
rz(pi/2) qregless[3];
sx qregless[3];
rz(pi/2) qregless[3];
barrier qregless[3];
measure qregless[0] -> c[0];
measure qregless[1] -> c[1];
measure qregless[2] -> c[2];
measure qregless[3] -> c[3];