from qiskit import QuantumRegister, ClassicalRegister, QuantumCircuit
from numpy import pi

qreg_qregless = QuantumRegister(4, 'qregless')
creg_c = ClassicalRegister(4, 'c')
circuit = QuantumCircuit(qreg_qregless, creg_c)

circuit.reset(qreg_qregless[0])
circuit.barrier(qreg_qregless[0])
circuit.barrier(qreg_qregless[0])
circuit.rz(pi / 2, qreg_qregless[0])
circuit.sx(qreg_qregless[0])
circuit.rz(pi / 2, qreg_qregless[0])
circuit.barrier(qreg_qregless[0])
circuit.rz(pi / 2, qreg_qregless[0])
circuit.sx(qreg_qregless[0])
circuit.rz(pi / 2, qreg_qregless[0])
circuit.reset(qreg_qregless[1])
circuit.barrier(qreg_qregless[1])
circuit.barrier(qreg_qregless[1])
circuit.rz(pi / 2, qreg_qregless[1])
circuit.sx(qreg_qregless[1])
circuit.rz(pi / 2, qreg_qregless[1])
circuit.barrier(qreg_qregless[1])
circuit.rz(pi / 2, qreg_qregless[1])
circuit.sx(qreg_qregless[1])
circuit.rz(pi / 2, qreg_qregless[1])
circuit.reset(qreg_qregless[2])
circuit.barrier(qreg_qregless[2])
circuit.barrier(qreg_qregless[2])
circuit.rz(pi / 2, qreg_qregless[2])
circuit.sx(qreg_qregless[2])
circuit.rz(pi / 2, qreg_qregless[2])
circuit.barrier(qreg_qregless[2])
circuit.rz(pi / 2, qreg_qregless[2])
circuit.sx(qreg_qregless[2])
circuit.rz(pi / 2, qreg_qregless[2])
circuit.reset(qreg_qregless[3])
circuit.barrier(qreg_qregless[3])
circuit.rz(pi / 2, qreg_qregless[3])
circuit.sx(qreg_qregless[3])
circuit.rz(pi / 2, qreg_qregless[3])
circuit.barrier(qreg_qregless[3])
circuit.rz(pi / 2, qreg_qregless[3])
circuit.sx(qreg_qregless[3])
circuit.rz(pi / 2, qreg_qregless[3])
circuit.barrier(qreg_qregless[3])
circuit.measure(qreg_qregless[0], creg_c[0])
circuit.measure(qreg_qregless[1], creg_c[1])
circuit.measure(qreg_qregless[2], creg_c[2])
circuit.measure(qreg_qregless[3], creg_c[3])